#!/bin/sh

if [ "$#" -lt 2 ]; then
  echo "expected a path to entities directory as first argument and path to directory for expanded code"
  exit 1
fi

pwd="$PWD/$1"; shift
tmp_dir_name="$1"; shift
flags="$@"

expand() {
  cp -a "$pwd/." "$tmp_dir_name/"
  cd "$tmp_dir_name"

  find src -type f | xargs -n1 sed -i "" 's/repositories!/print_repositories!/g'
  cargo expand $flags > expanded.rs
  cat expanded.rs |
    sed 's/::alloc/std/g' |
    sed 's/:: alloc/std/g' |
    sed 's/::itertools::__std_iter::IntoIterator/std::iter::IntoIterator/g' |
    sed 's/map(|((a, b), b)| (a, b, b))/map(|((a, b), c)| (a, b, c))/g' |
    sed 's/::core::panicking::panic("not yet implemented")/todo!()/g' > expanded2.rs
  cat expanded2.rs > expanded.rs
  rm expanded2.rs

  expanded=$(cat expanded.rs)
  start_line=$(echo "$expanded" | grep -n "pub trait" | head -1 | cut -f1 -d:)
  traits=$(echo "$expanded" | sed -n "$start_line"',$p')
  echo "$traits" > expanded.rs
  perl -0777 -pi -e 's/\s*\n\s+where\n\s+Self: ([A-z]+Repository)(\n\s+\+ [A-z]+Repository)*,\n\s*/ /g' expanded.rs
  cat expanded.rs
}

expand
